version: 43.0.9
pageUuid: f9d8a280-5196-11ee-a00e-ef66976c8a76
appTemplate:
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: true
      runtimeV2OptOut: false
  isGlobalWidget: true
  version: 3.2.2
  experimentalDataTabEnabled: true
