version: 43.0.9
pageUuid: 68bff358-7f35-11ee-8dd2-db054ea031d5
appTemplate:
  experimentalPerfFeatures:
    object:
      useRuntimeV2: true
      runtimeV2OptOut: false
  isGlobalWidget: true
  version: 3.14.13
  experimentalDataTabEnabled: true
