id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-10-29T02:30:03.461Z
blockData:
  top: 48
  left: 48
  uuid: a4aa3d48-f12a-4262-ae05-d277691aa729
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
