version: 43.0.9
pageUuid: 464f3338-518b-11ee-83e3-c33a5bd9f324
appTemplate:
  experimentalPerfFeatures:
    object:
      useRuntimeV2: true
      runtimeV2OptOut: false
  version: 3.12.0
  experimentalDataTabEnabled: true
