version: 43.0.9
pageUuid: d0c1e3d4-7e6e-11ee-86e2-03ea7c922ef7
appTemplate:
  experimentalPerfFeatures:
    object:
      useRuntimeV2: true
      runtimeV2OptOut: false
  shortlink: false
  version: 3.16.1
  experimentalDataTabEnabled: true
