<GlobalFunctions>
  <RESTQuery
    id="query1"
    query="json"
    resourceDisplayName="my_resource_again_again"
    resourceName="0ef973dd-18c7-41a1-a704-b6f31e5bd17e"
    resourceTypeOverride=""
  />
</GlobalFunctions>
