<App>
  <Frame
    id="$main"
    enableFullBleed={false}
    isHiddenOnDesktop={false}
    isHiddenOnMobile={false}
    paddingType="normal"
    sticky={null}
    type="main"
  >
    <Module
      id="myModule1"
      name="my_module"
      pageUuid="8311a51c-518b-11ee-945f-bbc563be752f"
    />
  </Frame>
</App>
